=== Amenay-khl/tux/src/xml/plateau.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           targetNamespace = "http://myGame/tux"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:tux="http://myGame/tux"
           elementFormDefault="qualified">

    <xs:element name="plateau" type="tux:Plateau"/>
    
    
    <xs:complexType name="Plateau">
        <xs:sequence>
            <xs:element name="dimension" type="tux:Dimension" />
            <xs:element name="mapping" type="tux:Mapping"/>
            <xs:element name="pion" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="Dimension">
        <xs:sequence>
            <xs:element name="height" type="xs:int"/>
            <xs:element name="width" type="xs:int"/>
            <xs:element name="depth" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="Mapping">
        <xs:sequence>
            <xs:element name="textureBottom" type="xs:string"/>
            <xs:element name="textureEast" type="xs:string"/>
            <xs:element name="textureWest" type="xs:string"/>
            <xs:element name="textureNorth" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    
    
    
    
</xs:schema>

=== Amenay-khl/tux/src/xml/plateau.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<pl:plateau xmlns:pl="http://myGame/tux"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:schemaLocation="http://myGame/tux plateau.xsd">
    <pl:dimension>
        <pl:height>60</pl:height>
        <pl:width>100</pl:width>
        <pl:depth>100</pl:depth>
    </pl:dimension>
    <pl:mapping>
        <pl:textureBottom>textures/floor/snow1.png</pl:textureBottom>
        <pl:textureEast>textures/skybox/interstellar/east.png</pl:textureEast>
        <pl:textureWest>textures/skybox/interstellar/west.png</pl:textureWest>
        <pl:textureNorth>textures/skybox/interstellar/north.png</pl:textureNorth>
    </pl:mapping>
    <pl:pion>
        une url
    </pl:pion>
</pl:plateau>
